version: '2.4'
services:
  ors-app-blog:
    container_name: ors-app-blog
    ports:
      - 8180:8080
      - 9001:9001
    # image: rcaroprese/ors:blog
    build:
        context: ../
    volumes:
        - ./data/graphs:/ors-core/data/graphs
        - ./data/elevation_cache:/ors-core/data/elevation_cache
        - ./logs/ors:/var/log/ors
        - ./logs/tomcat:/usr/local/tomcat/logs
    environment:
      - BUILD_GRAPHS=True
      - "JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:ParallelGCThreads=4 -Xms1g -Xmx2g"
      - "CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost"
